name: Quality & Release

on: [push]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    quality:
        name: Quality
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install
              uses: moonsworth/actions/setup-node@master
              with:
                  node_version: 20
                  node_scope: '@LunarClient'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  npm_token: ${{ secrets.NPM_TOKEN }}

            - name: Build Packages
              run: pnpm build

            - name: Run Tests
              run: pnpm test

            - name: Check Types
              run: pnpm types
    release:
        name: Release
        runs-on: ubuntu-latest
        needs: quality
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install
              uses: moonsworth/actions/setup-node@master
              with:
                  node_version: 20
                  node_scope: '@LunarClient'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  npm_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
